### ISSUE TITLE
麻烦老哥有空的时候看看这个插件

### ISSUE THREAD

**Issue by asports** [sbwml/luci-theme-argon#1]
首先我知道这个主题是老竭力做的，但他那边半死不活状态，issues基本没人回应。看到老哥这边有在更新，所以试着提个issues看看能不能修复一下。

下面是这个流量监控插件问题，是关于内容显示方面的

openwrt 23.05 默认bootstrap主题可以正常显示客户端ip+名称，argon主题只能显示客户端ip

插件来源 https://github.com/brvphoenix/luci-app-wrtbwmon

<img width="1610" alt="argon-mod" src="https://github.com/sbwml/luci-theme-argon/assets/153172868/f8a840fa-1d1b-4893-a238-38005ea2f4ca">

<img width="995" alt="bootstrap" src="https://github.com/sbwml/luci-theme-argon/assets/153172868/bb9b8e7f-a917-4ef2-8138-802be1ce42b5">

**Comment by sbwml** [comment]
修复 https://github.com/sbwml/luci-theme-argon/commit/6d07c9c8455f9612a27ba89cf8dd28dd85910e6e

![image](https://github.com/sbwml/luci-theme-argon/assets/16485166/ce0bf34d-49db-4e23-ab46-297e50a9fc8b)

**Comment by asports** [comment]
完美解决，谢谢老哥！
