### ISSUE TITLE
大佬主题在lean 6.6内核上有问题6.1还没测试

### ISSUE THREAD

**Issue by Dr-chen99** [sbwml/luci-theme-argon#2]
![1](https://github.com/user-attachments/assets/ba705fd3-3d9f-4732-bf6d-39682ce0e5b6)
左边没东西

**Comment by sbwml** [comment]
因为你找错地方了，你应该去用官方的 https://github.com/jerrykuku/luci-theme-argon

这里的主题只是个人用于 openwrt （官方，非其它来源）源码的 diy 版本。
