### ISSUE TITLE
麻烦一下大佬适配OpenClash移动端的web显示

### ISSUE THREAD

**Issue by xuanranran** [sbwml/luci-theme-argon#3]
超出边界的没办法滑动，只能看一半，订阅配置切换可以考虑一下原版主题风格~
![20241109202500](https://github.com/user-attachments/assets/3b8c7b9d-8747-4a59-bfdd-d1c6b9e3ae69)
![20241109202510](https://github.com/user-attachments/assets/3f40f487-ae6d-450c-ba74-9ef20571e6de)
![20241109202519](https://github.com/user-attachments/assets/3be83f29-2f5f-435d-8f11-4be04d14c16c)
![20241109202532](https://github.com/user-attachments/assets/95d1f1e2-7739-4c6b-ae30-1f3885af188a)
![20241109202541](https://github.com/user-attachments/assets/b0cd7c19-33c0-4d41-8413-1d5e0827089e)
![20241109202546](https://github.com/user-attachments/assets/7e8f6f15-b2ed-43b6-a930-7df8dfc79592)
![20241109202552](https://github.com/user-attachments/assets/165f90f8-0ead-4b29-bf8b-926d407e675b)
原版主题风格是这样的
![20241109203534](https://github.com/user-attachments/assets/5a747520-5e3d-4548-b0eb-62f2fd650207)

**Comment by sbwml** [comment]
有两个问题
第一个我没有openclash
第二个你问错地方了，主题作者在这里：https://github.com/jerrykuku/luci-theme-argon

**Comment by xuanranran** [comment]
> 有两个问题 第一个我没有openclash 第二个你问错地方了，主题作者在这里：https://github.com/jerrykuku/luci-theme-argon

感觉你比较厉害，所以来问你了，大佬尝试一下～
