### ISSUE TITLE
能否优化一下24.10 lua的TextValue控件样式

### ISSUE THREAD

**Issue by lwb1978** [sbwml/luci-theme-argon#4]
老大修改的[argon]很不错，在使用过程中发现了些小小的瑕疵，就是lua的TextValue样式跟其他控件不统一，比如passwall编辑节点中，xray的xhttp显示如下：

![image](https://github.com/user-attachments/assets/96c09b44-df4c-4137-8514-15925c20710d)

sing-box的ech显示如下：

![image](https://github.com/user-attachments/assets/c76e7bfa-5ff8-4cc1-8606-f3ab65698909)

希望老大有空的话可以优化一下。

**Comment by sbwml** [comment]
有空我试试看

发自我的iPhone

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-theme-argon/commit/fb36113d82b4c7924057c277dff58aab9487a1a3

**Comment by lwb1978** [comment]
赞
