### ISSUE TITLE
状态栏网络大小不一致！

### ISSUE THREAD

**Issue by xiaobaishu1** [sbwml/luci-theme-argon#5]
![image](https://github.com/user-attachments/assets/2b12fb4f-4704-4b68-96b5-119e82181077)

还有一个刷写固件上传后保留配置的勾选颜色过深！希望修复一下

**Comment by sbwml** [comment]
argon 仓库在这里的  https://github.com/jerrykuku/luci-theme-argon

这里这个不是原创。

**Comment by xiaobaishu1** [comment]
> argon 仓库在这里的 https://github.com/jerrykuku/luci-theme-argon
> 
> 这里这个不是原创。

大佬那边都好久不更新了！问题不少！有时间能修复一下么

**Comment by sbwml** [comment]
我改不了。。 [jerrykuku/luci-theme-argon](https://github.com/jerrykuku/luci-theme-argon) 应该本身就不存在你说的这些东西。
